### ISSUE TITLE
Tower Unlocking Bug

### ISSUE THREAD

**Issue by EpicGamer200245** [NKHook/NKHook5#19] opened 2023-02-11 21:03 UTC
**Describe the bug**
When NKHook adds towers to save, it will unlock anything in the game that requires you to unlock that tower. Such as in the tower building the towers are normally supposed to have a locked sprite on top of them, but the unlocking system now automatically removes that lock.

**Expected behavior**
NKHook to not unlock them.

**Comment by DisabledMallis** [comment] 2023-02-12 11:10
This was caused by all towers being marked as unlocked. Now, only modded towers will be marked as unlocked (which is necessary as the game won't cause them to unlock otherwise). Gonna have a fix out soon hopefully.

**Closed as completed** 2023-02-12 11:28 UTC
